/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace TrustMe {
  export type TradeStruct = {
    id: PromiseOrValue<BigNumberish>;
    seller: PromiseOrValue<string>;
    buyer: PromiseOrValue<string>;
    tokenToSell: PromiseOrValue<string>;
    tokenToBuy: PromiseOrValue<string>;
    amountOfTokenToSell: PromiseOrValue<BigNumberish>;
    amountOfTokenToBuy: PromiseOrValue<BigNumberish>;
    deadline: PromiseOrValue<BigNumberish>;
    status: PromiseOrValue<BigNumberish>;
  };

  export type TradeStructOutput = [
    BigNumber,
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    number
  ] & {
    id: BigNumber;
    seller: string;
    buyer: string;
    tokenToSell: string;
    tokenToBuy: string;
    amountOfTokenToSell: BigNumber;
    amountOfTokenToBuy: BigNumber;
    deadline: BigNumber;
    status: number;
  };
}

export interface TrustMeInterface extends utils.Interface {
  functions: {
    "addTrade(address,address,address,uint256,uint256,uint256)": FunctionFragment;
    "cancelTrade(uint256)": FunctionFragment;
    "checkExpiredTrades()": FunctionFragment;
    "confirmTrade(uint256)": FunctionFragment;
    "getPendingTradesIDs()": FunctionFragment;
    "getTrade(uint256)": FunctionFragment;
    "getTradeStatus(uint256)": FunctionFragment;
    "getTradesIDsByUser(address)": FunctionFragment;
    "pendingTradesIDs(uint256)": FunctionFragment;
    "tradeIDToTrade(uint256)": FunctionFragment;
    "userToTradesIDs(address,uint256)": FunctionFragment;
    "withdraw(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addTrade"
      | "cancelTrade"
      | "checkExpiredTrades"
      | "confirmTrade"
      | "getPendingTradesIDs"
      | "getTrade"
      | "getTradeStatus"
      | "getTradesIDsByUser"
      | "pendingTradesIDs"
      | "tradeIDToTrade"
      | "userToTradesIDs"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addTrade",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTrade",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "checkExpiredTrades",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confirmTrade",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingTradesIDs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTrade",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTradeStatus",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTradesIDsByUser",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingTradesIDs",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "tradeIDToTrade",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "userToTradesIDs",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "addTrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkExpiredTrades",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingTradesIDs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTradeStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTradesIDsByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingTradesIDs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tradeIDToTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userToTradesIDs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "TradeCanceled(uint256,address,address)": EventFragment;
    "TradeConfirmed(uint256,address,address)": EventFragment;
    "TradeCreated(uint256,address,address)": EventFragment;
    "TradeExpired(uint256,address,address)": EventFragment;
    "TradeWithdrawn(uint256,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TradeCanceled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeConfirmed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeExpired"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeWithdrawn"): EventFragment;
}

export interface TradeCanceledEventObject {
  tradeID: BigNumber;
  seller: string;
  buyer: string;
}
export type TradeCanceledEvent = TypedEvent<
  [BigNumber, string, string],
  TradeCanceledEventObject
>;

export type TradeCanceledEventFilter = TypedEventFilter<TradeCanceledEvent>;

export interface TradeConfirmedEventObject {
  tradeID: BigNumber;
  seller: string;
  buyer: string;
}
export type TradeConfirmedEvent = TypedEvent<
  [BigNumber, string, string],
  TradeConfirmedEventObject
>;

export type TradeConfirmedEventFilter = TypedEventFilter<TradeConfirmedEvent>;

export interface TradeCreatedEventObject {
  tradeID: BigNumber;
  seller: string;
  buyer: string;
}
export type TradeCreatedEvent = TypedEvent<
  [BigNumber, string, string],
  TradeCreatedEventObject
>;

export type TradeCreatedEventFilter = TypedEventFilter<TradeCreatedEvent>;

export interface TradeExpiredEventObject {
  tradeID: BigNumber;
  seller: string;
  buyer: string;
}
export type TradeExpiredEvent = TypedEvent<
  [BigNumber, string, string],
  TradeExpiredEventObject
>;

export type TradeExpiredEventFilter = TypedEventFilter<TradeExpiredEvent>;

export interface TradeWithdrawnEventObject {
  tradeID: BigNumber;
  seller: string;
  buyer: string;
}
export type TradeWithdrawnEvent = TypedEvent<
  [BigNumber, string, string],
  TradeWithdrawnEventObject
>;

export type TradeWithdrawnEventFilter = TypedEventFilter<TradeWithdrawnEvent>;

export interface TrustMe extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TrustMeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addTrade(
      _buyer: PromiseOrValue<string>,
      _tokenToSell: PromiseOrValue<string>,
      _tokenToBuy: PromiseOrValue<string>,
      _amountOfTokenToSell: PromiseOrValue<BigNumberish>,
      _amountOfTokenToBuy: PromiseOrValue<BigNumberish>,
      _tradePeriod: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    cancelTrade(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    checkExpiredTrades(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    confirmTrade(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getPendingTradesIDs(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    getTrade(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[TrustMe.TradeStructOutput]>;

    getTradeStatus(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getTradesIDsByUser(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    pendingTradesIDs(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    tradeIDToTrade(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        number
      ] & {
        id: BigNumber;
        seller: string;
        buyer: string;
        tokenToSell: string;
        tokenToBuy: string;
        amountOfTokenToSell: BigNumber;
        amountOfTokenToBuy: BigNumber;
        deadline: BigNumber;
        status: number;
      }
    >;

    userToTradesIDs(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    withdraw(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addTrade(
    _buyer: PromiseOrValue<string>,
    _tokenToSell: PromiseOrValue<string>,
    _tokenToBuy: PromiseOrValue<string>,
    _amountOfTokenToSell: PromiseOrValue<BigNumberish>,
    _amountOfTokenToBuy: PromiseOrValue<BigNumberish>,
    _tradePeriod: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  cancelTrade(
    _tradeID: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  checkExpiredTrades(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  confirmTrade(
    _tradeID: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getPendingTradesIDs(overrides?: CallOverrides): Promise<BigNumber[]>;

  getTrade(
    _tradeID: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<TrustMe.TradeStructOutput>;

  getTradeStatus(
    _tradeID: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<number>;

  getTradesIDsByUser(
    _user: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  pendingTradesIDs(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  tradeIDToTrade(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      string,
      string,
      string,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      number
    ] & {
      id: BigNumber;
      seller: string;
      buyer: string;
      tokenToSell: string;
      tokenToBuy: string;
      amountOfTokenToSell: BigNumber;
      amountOfTokenToBuy: BigNumber;
      deadline: BigNumber;
      status: number;
    }
  >;

  userToTradesIDs(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdraw(
    _tradeID: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addTrade(
      _buyer: PromiseOrValue<string>,
      _tokenToSell: PromiseOrValue<string>,
      _tokenToBuy: PromiseOrValue<string>,
      _amountOfTokenToSell: PromiseOrValue<BigNumberish>,
      _amountOfTokenToBuy: PromiseOrValue<BigNumberish>,
      _tradePeriod: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelTrade(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    checkExpiredTrades(overrides?: CallOverrides): Promise<void>;

    confirmTrade(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getPendingTradesIDs(overrides?: CallOverrides): Promise<BigNumber[]>;

    getTrade(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<TrustMe.TradeStructOutput>;

    getTradeStatus(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<number>;

    getTradesIDsByUser(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    pendingTradesIDs(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tradeIDToTrade(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        number
      ] & {
        id: BigNumber;
        seller: string;
        buyer: string;
        tokenToSell: string;
        tokenToBuy: string;
        amountOfTokenToSell: BigNumber;
        amountOfTokenToBuy: BigNumber;
        deadline: BigNumber;
        status: number;
      }
    >;

    userToTradesIDs(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "TradeCanceled(uint256,address,address)"(
      tradeID?: PromiseOrValue<BigNumberish> | null,
      seller?: PromiseOrValue<string> | null,
      buyer?: PromiseOrValue<string> | null
    ): TradeCanceledEventFilter;
    TradeCanceled(
      tradeID?: PromiseOrValue<BigNumberish> | null,
      seller?: PromiseOrValue<string> | null,
      buyer?: PromiseOrValue<string> | null
    ): TradeCanceledEventFilter;

    "TradeConfirmed(uint256,address,address)"(
      tradeID?: PromiseOrValue<BigNumberish> | null,
      seller?: PromiseOrValue<string> | null,
      buyer?: PromiseOrValue<string> | null
    ): TradeConfirmedEventFilter;
    TradeConfirmed(
      tradeID?: PromiseOrValue<BigNumberish> | null,
      seller?: PromiseOrValue<string> | null,
      buyer?: PromiseOrValue<string> | null
    ): TradeConfirmedEventFilter;

    "TradeCreated(uint256,address,address)"(
      tradeID?: PromiseOrValue<BigNumberish> | null,
      seller?: PromiseOrValue<string> | null,
      buyer?: PromiseOrValue<string> | null
    ): TradeCreatedEventFilter;
    TradeCreated(
      tradeID?: PromiseOrValue<BigNumberish> | null,
      seller?: PromiseOrValue<string> | null,
      buyer?: PromiseOrValue<string> | null
    ): TradeCreatedEventFilter;

    "TradeExpired(uint256,address,address)"(
      tradeID?: PromiseOrValue<BigNumberish> | null,
      seller?: PromiseOrValue<string> | null,
      buyer?: PromiseOrValue<string> | null
    ): TradeExpiredEventFilter;
    TradeExpired(
      tradeID?: PromiseOrValue<BigNumberish> | null,
      seller?: PromiseOrValue<string> | null,
      buyer?: PromiseOrValue<string> | null
    ): TradeExpiredEventFilter;

    "TradeWithdrawn(uint256,address,address)"(
      tradeID?: PromiseOrValue<BigNumberish> | null,
      seller?: PromiseOrValue<string> | null,
      buyer?: PromiseOrValue<string> | null
    ): TradeWithdrawnEventFilter;
    TradeWithdrawn(
      tradeID?: PromiseOrValue<BigNumberish> | null,
      seller?: PromiseOrValue<string> | null,
      buyer?: PromiseOrValue<string> | null
    ): TradeWithdrawnEventFilter;
  };

  estimateGas: {
    addTrade(
      _buyer: PromiseOrValue<string>,
      _tokenToSell: PromiseOrValue<string>,
      _tokenToBuy: PromiseOrValue<string>,
      _amountOfTokenToSell: PromiseOrValue<BigNumberish>,
      _amountOfTokenToBuy: PromiseOrValue<BigNumberish>,
      _tradePeriod: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    cancelTrade(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    checkExpiredTrades(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    confirmTrade(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getPendingTradesIDs(overrides?: CallOverrides): Promise<BigNumber>;

    getTrade(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTradeStatus(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTradesIDsByUser(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pendingTradesIDs(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tradeIDToTrade(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userToTradesIDs(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addTrade(
      _buyer: PromiseOrValue<string>,
      _tokenToSell: PromiseOrValue<string>,
      _tokenToBuy: PromiseOrValue<string>,
      _amountOfTokenToSell: PromiseOrValue<BigNumberish>,
      _amountOfTokenToBuy: PromiseOrValue<BigNumberish>,
      _tradePeriod: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    cancelTrade(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    checkExpiredTrades(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    confirmTrade(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getPendingTradesIDs(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTrade(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTradeStatus(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTradesIDsByUser(
      _user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pendingTradesIDs(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tradeIDToTrade(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userToTradesIDs(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      _tradeID: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
